### ISSUE TITLE
Merge R plugin to the asdf-community

### ISSUE THREAD

**Issue by taiar** [asdf-community/.github#18]
Hi folks,

based on the conversation we were having at this issue https://github.com/asdf-vm/asdf-plugins/issues/274, on the plugins repo, I was instructed to open this issue here.

Looks like it would be a nice thing to merge the R plugin on the asdf-community so we would have centralized management there. As I'm currently maintaining this plugin for the last few months, maybe it would be easier for me to help put the plugin code in shape and attend to the standards of the community ones.

This is the current repo for the R plugin: https://github.com/taiar/asdf-R

Please let me know how can I help to push this forward.
Thanks!

**Comment by smorimoto** [comment]
All the repository import process is already completed! Thank you @taiar!
