### ISSUE TITLE
Move `helmsman` plugin to the asdf-community org

### ISSUE THREAD

**Issue by luisdavim** [asdf-community/.github#23]
Hi,

I'm one of the maintainers from the [Helmsman](https://github.com/Praqma/helmsman) project, and I've just created an `asdf` plugin for it, currently in https://github.com/luisdavim/asdf-helmsman, but I'd like to move it to this community org.

Thanks,
Luis

**Comment by luisdavim** [comment]
I also have a PR to add the current repo to the list of plugins: https://github.com/asdf-vm/asdf-plugins/pull/510

**Comment by smorimoto** [comment]
I just added the asdf-helmsman team: https://github.com/asdf-community/infrastructure/commit/8ed3faec81231c99600331067d630f92db968b9f

**Comment by luisdavim** [comment]
I've been added to the github org, should I transfer my repo to it?

**Comment by smorimoto** [comment]
Yes

**Comment by luisdavim** [comment]
Done, the repo has been moved to https://github.com/asdf-community/asdf-helmsman

**Comment by smorimoto** [comment]
All set!
