### ISSUE TITLE
Welcome thread

### ISSUE THREAD

**Issue by imbsky** [asdf-community/.github#3]

**Comment by imbsky** [comment]
I have invited @nverno for some plugins such as SML, welcome! CC: @vic @schutm

**Comment by nverno** [comment]
Hey! I transferred asdf-sml to community

**Comment by imbsky** [comment]
Thank you!

**Comment by imbsky** [comment]
I just invited @odarriba. Welcome!

**Comment by odarriba** [comment]
Hey! 👋 

I have just transferred asdf-php to the community.

**Comment by imbsky** [comment]
Cool!

**Comment by imbsky** [comment]
I just invited @marciogm. Welcome!

**Comment by imbsky** [comment]
I just invited @mikestephens and @jeffryang24!

**Comment by imbsky** [comment]
I just invited @Naturalclar!

**Comment by imbsky** [comment]
I just invited @sasurau4.

**Comment by imbsky** [comment]
I just invited @looztra and @superbrothers as author, @nzws as maintainer.

**Comment by abatilo** [comment]
Could I apply for membership somewhere? I have a few plugins now and would like to donate them if possible.

**Comment by smorimoto** [comment]
To be honest, the member we need now is the maintainer of the plugin. The main focus now is on fixing broken tests in existing plugins and making the code better than donate. Of course, it's not unwelcome, but there is no guarantee that all of them will be maintainable by current maintainers, so we're being a little cautious about it.

**Comment by smorimoto** [comment]
​I created this repository to make our organization more open, so please check here for member invitations and deletions.
https://github.com/asdf-community/infrastructure

**Comment by abatilo** [comment]
If you have examples/links of where I can contribute, please let me know. I'm using `asdf` in many places so I'd be open to contribute more directly instead of just plugins.

**Comment by smorimoto** [comment]
@abatilo Sorry for the VERY late reply. You can probably refer the process in this discussion to contribute your plugin. Detailed documentation to do that is still in the works, but will be available soon. https://github.com/asdf-community/.github/discussions/11
