### ISSUE TITLE
Move `quarkus` plugin to asdf-community

### ISSUE THREAD

**Issue by marcwrobel** [asdf-community/.github#31]
I just wrote a plugin for managing [Quarkus CLI](https://quarkus.io/guides/cli-tooling) versions, https://github.com/marcwrobel/asdf-quarkus, and I would like to move my plugin into https://github.com/asdf-community.

Let me know if you need additional details.

**Comment by marcwrobel** [comment]
I also have a PR to add the current repo to the list of plugins: https://github.com/asdf-vm/asdf-plugins/pull/611.

**Comment by smorimoto** [comment]
I just invited you to the team: https://github.com/asdf-community/infrastructure/commit/5510b89bdc8e0135533ca3af894623ea3fc1675e

**Comment by marcwrobel** [comment]
Thanks, I just moved the repository to asdf-community. I updated the docs, but I am not sure what to do with [the LICENCE file](https://github.com/asdf-community/asdf-quarkus/blob/main/LICENSE). Should I replace my name @smorimoto ? With what ?

**Comment by smorimoto** [comment]
I'm not qualified as a lawyer, but I think there is no problem legally to replace the name or not.
