### ISSUE TITLE
Move asdf-pdm here

### ISSUE THREAD

**Issue by 1oglop1** [asdf-community/.github#33]
Hello, I created a plugin https://github.com/1oglop1/asdf-pdm for python packaging tool called [pdm](https://github.com/pdm-project/pdm)
It would be nice if I can move it here.
@vic  @smorimoto

**Comment by smorimoto** [comment]
I just invited you to the team: https://github.com/asdf-community/infrastructure/commit/352bb329a52b9189b1fa6c6c3f081366ce2bec78

**Comment by 1oglop1** [comment]
@smorimoto Great, thank you. I'll be able to move the repo within a couple days.

**Comment by smorimoto** [comment]
Any updates?

**Comment by 1oglop1** [comment]
Hi, sorry I lost contact with `pdm`. 

--> `Moving repository to asdf-community/asdf-pdm. This may take a few minutes.`

**Comment by smorimoto** [comment]
No worries at all 🙂

**Comment by smorimoto** [comment]
addressed in https://github.com/asdf-community/infrastructure/pull/22
