### ISSUE TITLE
"This CODEOWNERS file contains errors"

### ISSUE THREAD

**Issue by bcdady** [asdf-community/.github#36]
It looks like [CODEOWNERS](https://github.com/asdf-community/.github/blob/master/.github/CODEOWNERS) should not include the `/.github` text.

Screenshot:
![Screenshot](https://user-images.githubusercontent.com/2688689/185838034-5a04a613-863d-4fca-b904-494467639b9a.png)

**Comment by smorimoto** [comment]
Fixed in https://github.com/asdf-community/infrastructure/commit/dce17ee4e34fa59f16da56317b0f319898357a8b.
