### ISSUE TITLE
move `asdf-golang` here

### ISSUE THREAD

**Issue by andrew-werdna** [asdf-community/.github#40]
I'm not the author, but I have used this plugin and found it extremely helpful, effective, and without problems. I would like to request that we allow [asdf-golang](https://github.com/kennyp/asdf-golang) to be listed in the community plugin list, if that is acceptable to the author and this community. Linking to the author's GH profile: [kennyp](https://github.com/kennyp)

**Comment by smorimoto** [comment]
CC: @kennyp

**Comment by kennyp** [comment]
Thanks for the mention. What are the implications? I just want to make sure I understand what I'm committing to.

**Comment by smorimoto** [comment]
Basically, what we're going to do here:

1. Create a team under this organization with the same name as the repository
2. Make the team the repository administrator
3. After the repository is transferred, GitHub can handle it with appropriate redirection, so no additional effort is required

Everything in this organization is managed with Terraform code, and everyone's every privilege is managed openly. If you're interested in that as well, check out this repository: https://github.com/asdf-community/infrastructure

**Comment by kennyp** [comment]
Cool, so would you create a PR to add the team and make me a member? Then I would add the team as an admin to the repo?

**Comment by smorimoto** [comment]
The next step is for me to create a team. You will then be invited to the organization and will simply transfer the repository to the organization. Then I will take care of Terraform for the repository.

**Comment by smorimoto** [comment]
I just invited you to the team: https://github.com/asdf-community/infrastructure/commit/452c3021453aa10f555bbcdb244b5193ad6deb83

**Comment by andrew-werdna** [comment]
BTW @kennyp I would happily contribute or help out in whatever way is acceptable to you

**Comment by kennyp** [comment]
> I just invited you to the team: [asdf-community/infrastructure@452c302](https://github.com/asdf-community/infrastructure/commit/452c3021453aa10f555bbcdb244b5193ad6deb83)

@smorimoto :cool:, so now I just transfer the repo to `asdf-community` correct?

**Comment by kennyp** [comment]
> BTW @kennyp I would happily contribute or help out in whatever way is acceptable to you

Very much appreciated @andrew-werdna. There are a few open issues if you want to take a look.

**Comment by smorimoto** [comment]
> @smorimoto 🆒, so now I just transfer the repo to asdf-community correct?

@kennyp Yes.

**Comment by smorimoto** [comment]
Great!

**Comment by smorimoto** [comment]
See https://github.com/asdf-community/infrastructure/pull/23
